[package]
name = "solarity-rendering"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
ash.workspace = true
glam.workspace = true
solarity-asset.workspace = true
solarity-cpu.workspace = true
solarity-ecs.workspace = true
thiserror.workspace = true
tracing.workspace = true
vk-mem.workspace = true

[build-dependencies]
shaderc.workspace = true

[lints]
workspace = true

[dev-dependencies]
sdl3.workspace = true
wow-adt.workspace = true
wow-m2.workspace = true
wow-mpq.workspace = true
wow-wdt.workspace = true
