//! Event names created by the stock Glue manager before UI construction.

/// Resolves `name` to the canonical Glue event spelling.
pub(super) fn glue_event(name: &str) -> Option<&'static str> {
    GLUE_EVENTS
        .iter()
        .copied()
        .find(|event| event.eq_ignore_ascii_case(name))
}

const GLUE_EVENTS: [&str; 41] = [
    "SET_GLUE_SCREEN",
    "START_GLUE_MUSIC",
    "DISCONNECTED_FROM_SERVER",
    "OPEN_STATUS_DIALOG",
    "UPDATE_STATUS_DIALOG",
    "CLOSE_STATUS_DIALOG",
    "ADDON_LIST_UPDATE",
    "CHARACTER_LIST_UPDATE",
    "UPDATE_SELECTED_CHARACTER",
    "OPEN_REALM_LIST",
    "GET_PREFERRED_REALM_INFO",
    "UPDATE_SELECTED_RACE",
    "SELECT_LAST_CHARACTER",
    "SELECT_FIRST_CHARACTER",
    "GLUE_SCREENSHOT_SUCCEEDED",
    "GLUE_SCREENSHOT_FAILED",
    "PATCH_UPDATE_PROGRESS",
    "PATCH_DOWNLOADED",
    "SUGGEST_REALM",
    "SUGGEST_REALM_WRONG_PVP",
    "SUGGEST_REALM_WRONG_CATEGORY",
    "SHOW_SERVER_ALERT",
    "FRAMES_LOADED",
    "FORCE_RENAME_CHARACTER",
    "FORCE_DECLINE_CHARACTER",
    "SHOW_SURVEY_NOTIFICATION",
    "PLAYER_ENTER_PIN",
    "CLIENT_ACCOUNT_MISMATCH",
    "PLAYER_ENTER_MATRIX",
    "SCANDLL_ERROR",
    "SCANDLL_DOWNLOADING",
    "SCANDLL_FINISHED",
    "SERVER_SPLIT_NOTICE",
    "TIMER_ALERT",
    "ACCOUNT_MESSAGES_AVAILABLE",
    "ACCOUNT_MESSAGES_HEADERS_LOADED",
    "ACCOUNT_MESSAGES_BODY_LOADED",
    "CLIENT_TRIAL",
    "PLAYER_ENTER_TOKEN",
    "GAME_ACCOUNTS_UPDATED",
    "CLIENT_CONVERTED",
];
