//! Closed liquid shader families and their build-generated SPIR-V modules.

/// The ordinary programmable liquid families selected by native 8A1FA0.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum LiquidShader {
    /// Animated surface plus lit depth and the stock specular contribution.
    Water,
    /// The stock water path with specular disabled.
    WaterNoSpecular,
    /// Opaque animated magma/slime, modulated by vertex color.
    Magma,
}

/// Immutable modules compiled from exact stock ps_2_0/vs_2_0 shader contracts.
pub struct LiquidSpirvProgram {
    shader: LiquidShader,
    vertex_words: Box<[u32]>,
    fragment_words: Box<[u32]>,
}

impl LiquidSpirvProgram {
    /// Selects validated bytecode generated by the Cargo build.
    #[must_use]
    pub fn for_shader(shader: LiquidShader) -> Self {
        let (vertex, fragment): (&[u8], &[u8]) = match shader {
            LiquidShader::Water => (
                include_bytes!(concat!(env!("OUT_DIR"), "/liquid-water.vert.spv")),
                include_bytes!(concat!(env!("OUT_DIR"), "/liquid-water.frag.spv")),
            ),
            LiquidShader::WaterNoSpecular => (
                include_bytes!(concat!(
                    env!("OUT_DIR"),
                    "/liquid-water-no-specular.vert.spv"
                )),
                include_bytes!(concat!(
                    env!("OUT_DIR"),
                    "/liquid-water-no-specular.frag.spv"
                )),
            ),
            LiquidShader::Magma => (
                include_bytes!(concat!(env!("OUT_DIR"), "/liquid-magma.vert.spv")),
                include_bytes!(concat!(env!("OUT_DIR"), "/liquid-magma.frag.spv")),
            ),
        };
        Self {
            shader,
            vertex_words: words(vertex),
            fragment_words: words(fragment),
        }
    }

    /// Returns the native shader family represented by these modules.
    #[must_use]
    pub const fn shader(&self) -> LiquidShader {
        self.shader
    }

    /// Returns the vertex stage in SPIR-V word order.
    #[must_use]
    pub fn vertex_words(&self) -> &[u32] {
        &self.vertex_words
    }

    /// Returns the fragment stage in SPIR-V word order.
    #[must_use]
    pub fn fragment_words(&self) -> &[u32] {
        &self.fragment_words
    }
}

/// Decodes the complete word-aligned modules already validated by the build.
fn words(bytes: &[u8]) -> Box<[u32]> {
    bytes
        .as_chunks::<4>()
        .0
        .iter()
        .map(|word| u32::from_le_bytes(*word))
        .collect()
}
