//! Selection of build-generated ordinary-particle SPIR-V.

use super::source::{PARTICLE_FRAGMENT_SPIRV, PARTICLE_VERTEX_SPIRV};
use super::{M2ParticleSpirvError, M2ParticleSpirvProgram};
use crate::M2MaterialState;

/// Selector for immutable particle bytecode generated during the Cargo build.
pub struct M2ParticleSpirvCompiler;

impl M2ParticleSpirvCompiler {
    /// Creates the compiler used by the renderer's particle pipeline registry.
    ///
    /// # Errors
    ///
    /// Build-generated bytecode has no fallible runtime initialization.
    pub fn new() -> Result<Self, M2ParticleSpirvError> {
        Ok(Self)
    }

    /// Selects the PNC0T0 shader pair for one synthesized stock material.
    ///
    /// # Errors
    ///
    /// Bytecode validity was enforced by the build script.
    pub fn compile(
        &self,
        material: M2MaterialState,
    ) -> Result<M2ParticleSpirvProgram, M2ParticleSpirvError> {
        Ok(M2ParticleSpirvProgram::new(
            material,
            spirv_words(PARTICLE_VERTEX_SPIRV),
            spirv_words(PARTICLE_FRAGMENT_SPIRV),
            [u32::from(!material.is_unlit())],
            [
                material.alpha_reference(1.0).to_bits(),
                material.fog_mode() as u32,
            ],
        ))
    }
}

fn spirv_words(bytes: &[u8]) -> Vec<u32> {
    bytes
        .as_chunks::<4>()
        .0
        .iter()
        .map(|word| u32::from_le_bytes([word[0], word[1], word[2], word[3]]))
        .collect()
}
