//! Selection of build-generated ordinary-particle SPIR-V.

use std::sync::{Arc, OnceLock};

use super::source::{PARTICLE_FRAGMENT_SPIRV, PARTICLE_VERTEX_SPIRV};
use super::{M2ParticleSpirvError, M2ParticleSpirvProgram};
use crate::M2MaterialState;

/// Selector for immutable particle bytecode generated during the Cargo build.
pub struct M2ParticleSpirvCompiler;

impl M2ParticleSpirvCompiler {
    /// Creates the compiler used by the renderer's particle pipeline registry.
    ///
    /// # Errors
    ///
    /// Build-generated bytecode has no fallible runtime initialization.
    pub fn new() -> Result<Self, M2ParticleSpirvError> {
        Ok(Self)
    }

    /// Selects the PNC0T0 shader pair for one synthesized stock material.
    ///
    /// # Errors
    ///
    /// Bytecode validity was enforced by the build script.
    pub fn compile(
        &self,
        material: M2MaterialState,
    ) -> Result<M2ParticleSpirvProgram, M2ParticleSpirvError> {
        Ok(M2ParticleSpirvProgram::new(
            material,
            retained_spirv_words(PARTICLE_VERTEX_SPIRV, &PARTICLE_VERTEX_WORDS),
            retained_spirv_words(PARTICLE_FRAGMENT_SPIRV, &PARTICLE_FRAGMENT_WORDS),
            [u32::from(!material.is_unlit())],
            [material.fog_mode() as u32],
        ))
    }
}

static PARTICLE_VERTEX_WORDS: OnceLock<Arc<[u32]>> = OnceLock::new();
static PARTICLE_FRAGMENT_WORDS: OnceLock<Arc<[u32]>> = OnceLock::new();

/// Converts one embedded particle module once for every material specialization.
fn retained_spirv_words(bytes: &[u8], words: &OnceLock<Arc<[u32]>>) -> Arc<[u32]> {
    Arc::clone(words.get_or_init(|| {
        bytes
            .as_chunks::<4>()
            .0
            .iter()
            .map(|word| u32::from_le_bytes([word[0], word[1], word[2], word[3]]))
            .collect()
    }))
}
