//! Selection of build-generated ribbon SPIR-V.

use super::source::{RIBBON_FRAGMENT_SPIRV, RIBBON_VERTEX_SPIRV};
use super::{M2RibbonSpirvError, M2RibbonSpirvProgram};
use crate::M2MaterialState;

/// Selector for immutable ribbon bytecode generated during the Cargo build.
pub struct M2RibbonSpirvCompiler;

impl M2RibbonSpirvCompiler {
    /// Creates the compiler used by the renderer's ribbon pipeline registry.
    ///
    /// # Errors
    ///
    /// Build-generated bytecode has no fallible runtime initialization.
    pub fn new() -> Result<Self, M2RibbonSpirvError> {
        Ok(Self)
    }

    /// Selects the PCT0 shader pair for one exact stock material state.
    ///
    /// # Errors
    ///
    /// Bytecode validity was enforced by the build script.
    pub fn compile(
        &self,
        material: M2MaterialState,
    ) -> Result<M2RibbonSpirvProgram, M2RibbonSpirvError> {
        Ok(M2RibbonSpirvProgram::new(
            material,
            spirv_words(RIBBON_VERTEX_SPIRV),
            spirv_words(RIBBON_FRAGMENT_SPIRV),
            [material.alpha_reference(1.0).to_bits()],
        ))
    }
}

fn spirv_words(bytes: &[u8]) -> Vec<u32> {
    bytes
        .as_chunks::<4>()
        .0
        .iter()
        .map(|word| u32::from_le_bytes([word[0], word[1], word[2], word[3]]))
        .collect()
}
