//! Selection of build-generated ribbon SPIR-V.

use std::sync::{Arc, OnceLock};

use solarity_asset::M2BlendMode;

use super::source::{RIBBON_FRAGMENT_SPIRV, RIBBON_VERTEX_SPIRV};
use super::{M2RibbonSpirvError, M2RibbonSpirvProgram};
use crate::M2MaterialState;

/// Selector for immutable ribbon bytecode generated during the Cargo build.
pub struct M2RibbonSpirvCompiler;

impl M2RibbonSpirvCompiler {
    /// Creates the compiler used by the renderer's ribbon pipeline registry.
    ///
    /// # Errors
    ///
    /// Build-generated bytecode has no fallible runtime initialization.
    pub fn new() -> Result<Self, M2RibbonSpirvError> {
        Ok(Self)
    }

    /// Selects the PCT0 shader pair for one exact stock material state.
    ///
    /// # Errors
    ///
    /// Bytecode validity was enforced by the build script.
    pub fn compile(
        &self,
        material: M2MaterialState,
    ) -> Result<M2RibbonSpirvProgram, M2RibbonSpirvError> {
        Ok(M2RibbonSpirvProgram::new(
            material,
            retained_spirv_words(RIBBON_VERTEX_SPIRV, &RIBBON_VERTEX_WORDS),
            retained_spirv_words(RIBBON_FRAGMENT_SPIRV, &RIBBON_FRAGMENT_WORDS),
            // Ribbon submission restores GX's static alpha reference through
            // 873EE0. GX blend 10 has no alpha test; alpha-key uses the byte
            // reference multiplied by GX's reciprocal (without owner alpha).
            [match material.blend_mode() {
                M2BlendMode::Opaque | M2BlendMode::NoAlphaAdd => 0.0f32,
                M2BlendMode::AlphaKey => 224.0 * (1.0f32 / 255.0),
                _ => 1.0f32 / 255.0,
            }
            .to_bits()],
        ))
    }
}

static RIBBON_VERTEX_WORDS: OnceLock<Arc<[u32]>> = OnceLock::new();
static RIBBON_FRAGMENT_WORDS: OnceLock<Arc<[u32]>> = OnceLock::new();

/// Converts one embedded ribbon module once for every material specialization.
fn retained_spirv_words(bytes: &[u8], words: &OnceLock<Arc<[u32]>>) -> Arc<[u32]> {
    Arc::clone(words.get_or_init(|| {
        bytes
            .as_chunks::<4>()
            .0
            .iter()
            .map(|word| u32::from_le_bytes([word[0], word[1], word[2], word[3]]))
            .collect()
    }))
}
