//! Build-12340 CVar metadata registered before built-in UI execution.

/// Immutable native metadata for one case-insensitive console variable.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(super) struct UiCVarDefinition {
    pub(super) name: &'static str,
    pub(super) default: &'static str,
    pub(super) minimum: Option<f64>,
    pub(super) maximum: Option<f64>,
    pub(super) read_only: bool,
}

/// Declares a stock string CVar without native numeric boundaries.
const fn value(name: &'static str, default: &'static str) -> UiCVarDefinition {
    UiCVarDefinition {
        name,
        default,
        minimum: None,
        maximum: None,
        read_only: false,
    }
}

/// Declares a stock numeric CVar and its native inclusive boundaries.
const fn ranged(
    name: &'static str,
    default: &'static str,
    minimum: f64,
    maximum: f64,
) -> UiCVarDefinition {
    UiCVarDefinition {
        name,
        default,
        minimum: Some(minimum),
        maximum: Some(maximum),
        read_only: false,
    }
}

/// Native variables needed before GlueXML and FrameXML can execute.
///
/// The first group is consumed by login, video, audio, and native subsystem
/// startup. The second group is the stock Interface-options catalog whose
/// defaults were queried directly from build 12340 with `GetCVarDefault`.
pub(super) const STOCK_INITIAL_DEFINITIONS: &[UiCVarDefinition] = &[
    value("accountName", ""),
    value("accountList", ""),
    ranged("playIntroMovie", "1", 0.0, 1.0),
    // Enabled by default in build 12340's native performance display.
    ranged("showfps", "1", 0.0, 1.0),
    ranged("readTOS", "-1", -1.0, 1.0),
    ranged("readEULA", "-1", -1.0, 1.0),
    ranged("readTerminationWithoutNotice", "-1", -1.0, 1.0),
    ranged("readScanning", "-1", -1.0, 1.0),
    ranged("readContest", "-1", -1.0, 1.0),
    value("showToolsUI", "-1"),
    ranged("useUiScale", "0", 0.0, 1.0),
    ranged("uiScale", "1", 0.64, 1.0),
    ranged("gxVSync", "1", 0.0, 1.0),
    ranged("gxTripleBuffer", "0", 0.0, 1.0),
    ranged("gxCursor", "1", 0.0, 1.0),
    ranged("gxFixLag", "0", 0.0, 1.0),
    ranged("gxWindow", "0", 0.0, 1.0),
    ranged("gxMaximize", "0", 0.0, 1.0),
    ranged("windowResizeLock", "0", 0.0, 1.0),
    ranged("desktopGamma", "0", 0.0, 1.0),
    ranged("gamma", "1", 0.5, 1.5),
    value("gxResolution", "1920x1080"),
    ranged("gxRefresh", "60", 0.0, 1_000.0),
    ranged("gxMultisample", "1", 1.0, 8.0),
    ranged("farclip", "777", 177.0, 1_277.0),
    ranged("shadowLevel", "0", 0.0, 1.0),
    ranged("particleDensity", "1", 0.1, 1.0),
    ranged("environmentDetail", "1", 0.5, 1.5),
    ranged("groundEffectDensity", "64", 16.0, 64.0),
    ranged("groundEffectDist", "140", 70.0, 140.0),
    ranged("BaseMip", "0", 0.0, 1.0),
    ranged("extShadowQuality", "2", 0.0, 5.0),
    ranged("textureFilteringMode", "3", 0.0, 5.0),
    ranged("weatherDensity", "3", 0.0, 3.0),
    ranged("componentTextureLevel", "9", 8.0, 9.0),
    ranged("specular", "1", 0.0, 1.0),
    ranged("ffxGlow", "1", 0.0, 1.0),
    ranged("ffxDeath", "1", 0.0, 1.0),
    ranged("projectedTextures", "1", 0.0, 1.0),
    ranged("gxStereoEnabled", "0", 0.0, 1.0),
    ranged("gxStereoConvergence", "1", 0.2, 50.0),
    ranged("gxStereoSeparation", "0", 0.0, 100.0),
    ranged("Sound_EnableAllSound", "1", 0.0, 1.0),
    ranged("Sound_EnableSFX", "1", 0.0, 1.0),
    ranged("Sound_EnableMusic", "1", 0.0, 1.0),
    ranged("Sound_EnableAmbience", "1", 0.0, 1.0),
    ranged("Sound_EnableErrorSpeech", "1", 0.0, 1.0),
    ranged("Sound_EnableEmoteSounds", "1", 0.0, 1.0),
    ranged("Sound_EnablePetSounds", "1", 0.0, 1.0),
    ranged("Sound_EnableDSPEffects", "1", 0.0, 1.0),
    ranged("Sound_EnableReverb", "0", 0.0, 1.0),
    ranged("Sound_EnableHardware", "0", 0.0, 1.0),
    ranged("Sound_EnableSoftwareHRTF", "0", 0.0, 1.0),
    ranged("Sound_EnableSoundWhenGameIsInBG", "0", 0.0, 1.0),
    ranged("Sound_ListenerAtCharacter", "1", 0.0, 1.0),
    ranged("Sound_MasterVolume", "1", 0.0, 1.0),
    ranged("Sound_SFXVolume", "1", 0.0, 1.0),
    ranged("Sound_MusicVolume", "0.4", 0.0, 1.0),
    ranged("Sound_AmbienceVolume", "0.6", 0.0, 1.0),
    ranged("Sound_NumChannels", "64", 32.0, 64.0),
    value("Sound_MaxCacheSizeInBytes", "16777216"),
    value("Sound_MaxCacheableSizeInBytes", "1048576"),
    ranged("Sound_OutputQuality", "2", 0.0, 2.0),
    value("Sound_OutputDriverIndex", "0"),
    value("Sound_VoiceChatInputDriverIndex", "0"),
    value("Sound_VoiceChatOutputDriverIndex", "0"),
    ranged("Sound_ZoneMusicNoDelay", "0", 0.0, 1.0),
    // Zero selects push-to-talk; one selects voice activation.
    value("VoiceChatMode", "0"),
    ranged("advancedWorldMap", "0", 0.0, 1.0),
    ranged("assistAttack", "0", 0.0, 1.0),
    ranged("autoClearAFK", "0", 0.0, 1.0),
    ranged("autoDismountFlying", "0", 0.0, 1.0),
    ranged("autoInteract", "0", 0.0, 1.0),
    ranged("autoQuestProgress", "1", 0.0, 1.0),
    ranged("autoQuestWatch", "1", 0.0, 1.0),
    ranged("autoRangedCombat", "1", 0.0, 1.0),
    ranged("autoSelfCast", "1", 0.0, 1.0),
    ranged("blockTrades", "0", 0.0, 1.0),
    value("cameraBobbing", "0"),
    value("cameraPitchMoveSpeed", "90"),
    value("cameraPitchSmoothSpeed", "45"),
    value("cameraPivot", "1"),
    value("cameraSmoothStyle", "4"),
    value("cameraSmoothTrackingStyle", "4"),
    value("cameraTerrainTilt", "0"),
    value("cameraWaterCollision", "1"),
    value("cameraYawMoveSpeed", "180"),
    value("cameraYawSmoothSpeed", "180"),
    ranged("chatBubblesParty", "1", 0.0, 1.0),
    ranged("chatBubbles", "1", 0.0, 1.0),
    ranged("chatMouseScroll", "1", 0.0, 1.0),
    value("chatStyle", "im"),
    ranged("colorblindMode", "0", 0.0, 1.0),
    ranged("combatDamage", "1", 0.0, 1.0),
    ranged("combatHealing", "1", 0.0, 1.0),
    ranged("combatLogPeriodicSpells", "1", 0.0, 1.0),
    ranged("consolidateBuffs", "0", 0.0, 1.0),
    value("conversationMode", "popout"),
    ranged("deselectOnClick", "1", 0.0, 1.0),
    ranged("displayFreeBagSlots", "0", 0.0, 1.0),
    ranged("enableWowMouse", "0", 0.0, 1.0),
    ranged("fctSpellMechanics", "0", 0.0, 1.0),
    ranged("fctSpellMechanicsOther", "0", 0.0, 1.0),
    ranged("removeChatDelay", "0", 0.0, 1.0),
    ranged("showNewbieTips", "1", 0.0, 1.0),
    ranged("lockActionBars", "0", 0.0, 1.0),
    ranged("buffDurations", "0", 0.0, 1.0),
    ranged("alwaysShowActionBars", "0", 0.0, 1.0),
    ranged("showPartyPets", "1", 0.0, 1.0),
    ranged("questFadingDisable", "0", 0.0, 1.0),
    ranged("showPartyBackground", "0", 0.0, 1.0),
    ranged("hidePartyInRaid", "0", 0.0, 1.0),
    ranged("showTargetOfTarget", "0", 0.0, 1.0),
    ranged("targetOfTargetMode", "5", 0.0, 5.0),
    ranged("displayWorldPVPObjectives", "2", 0.0, 2.0),
    ranged("lootUnderMouse", "0", 0.0, 1.0),
    ranged("autoLootDefault", "0", 0.0, 1.0),
    ranged("enableCombatText", "1", 0.0, 1.0),
    ranged("fctLowManaHealth", "1", 0.0, 1.0),
    ranged("fctAuras", "0", 0.0, 1.0),
    ranged("fctCombatState", "0", 0.0, 1.0),
    ranged("fctDodgeParryMiss", "0", 0.0, 1.0),
    ranged("fctDamageReduction", "0", 0.0, 1.0),
    ranged("fctRepChanges", "0", 0.0, 1.0),
    ranged("fctReactives", "0", 0.0, 1.0),
    ranged("fctFriendlyHealers", "0", 0.0, 1.0),
    ranged("fctComboPoints", "0", 0.0, 1.0),
    ranged("fctEnergyGains", "0", 0.0, 1.0),
    ranged("fctPeriodicEnergyGains", "0", 0.0, 1.0),
    ranged("combatTextFloatMode", "1", 1.0, 3.0),
    ranged("fctHonorGains", "0", 0.0, 1.0),
    ranged("showCastableBuffs", "0", 0.0, 1.0),
    ranged("showDispelDebuffs", "1", 0.0, 1.0),
    ranged("showArenaEnemyFrames", "1", 0.0, 1.0),
    ranged("showArenaEnemyCastbar", "1", 0.0, 1.0),
    ranged("showArenaEnemyPets", "1", 0.0, 1.0),
    ranged("showCastableDebuffs", "0", 0.0, 1.0),
    ranged("fullSizeFocusFrame", "0", 0.0, 1.0),
    ranged("guildMemberNotify", "0", 0.0, 1.0),
    ranged("guildRecruitmentChannel", "1", 0.0, 1.0),
    value("locale", "enUS"),
    ranged("mapQuestDifficulty", "0", 0.0, 1.0),
    ranged("movieSubtitle", "0", 0.0, 1.0),
    ranged("checkAddonVersion", "1", 0.0, 1.0),
    ranged("nameplateAllowOverlap", "1", 0.0, 1.0),
    ranged("nameplateShowEnemyGuardians", "1", 0.0, 1.0),
    ranged("nameplateShowEnemyPets", "1", 0.0, 1.0),
    ranged("nameplateShowEnemyTotems", "1", 0.0, 1.0),
    ranged("nameplateShowFriendlyGuardians", "1", 0.0, 1.0),
    ranged("nameplateShowFriendlyPets", "1", 0.0, 1.0),
    ranged("nameplateShowFriendlyTotems", "1", 0.0, 1.0),
    ranged("partyStatusText", "0", 0.0, 1.0),
    ranged("partyBackgroundOpacity", "0.5", 0.0, 1.0),
    ranged("petMeleeDamage", "1", 0.0, 1.0),
    ranged("petSpellDamage", "1", 0.0, 1.0),
    ranged("petStatusText", "0", 0.0, 1.0),
    ranged("playerStatusText", "0", 0.0, 1.0),
    // Empty means FrameXML has not persisted a paper-doll stat category yet.
    value("playerStatLeftDropdown", ""),
    value("playerStatRightDropdown", ""),
    ranged("profanityFilter", "1", 0.0, 1.0),
    ranged("rotateMinimap", "0", 0.0, 1.0),
    ranged("screenEdgeFlash", "1", 0.0, 1.0),
    ranged("secureAbilityToggle", "1", 0.0, 1.0),
    ranged("showClassColorInNameplate", "0", 0.0, 1.0),
    ranged("showClock", "1", 0.0, 1.0),
    ranged("timeMgrUseMilitaryTime", "0", 0.0, 1.0),
    ranged("timeMgrUseLocalTime", "0", 0.0, 1.0),
    value("timeMgrAlarmTime", "0"),
    value("timeMgrAlarmMessage", ""),
    ranged("timeMgrAlarmEnabled", "0", 0.0, 1.0),
    value("lastTalkedToGM", ""),
    // Registered by the native world-map subsystem with the stock false
    // scalar at 0x009e14a0 in build 12340.
    ranged("showBattlefieldMinimap", "0", 0.0, 1.0),
    ranged("showItemLevel", "0", 0.0, 1.0),
    ranged("showLootSpam", "1", 0.0, 1.0),
    ranged("showRaidRange", "0", 0.0, 1.0),
    ranged("showTargetCastbar", "1", 0.0, 1.0),
    value("showTimestamps", "none"),
    ranged("showToastBroadcast", "1", 0.0, 1.0),
    ranged("showToastConversation", "1", 0.0, 1.0),
    ranged("showToastFriendRequest", "1", 0.0, 1.0),
    ranged("showToastOffline", "1", 0.0, 1.0),
    ranged("showToastOnline", "1", 0.0, 1.0),
    ranged("showToastWindow", "1", 0.0, 1.0),
    ranged("showVKeyCastbar", "1", 0.0, 1.0),
    ranged("ShowAllSpellRanks", "1", 0.0, 1.0),
    ranged("spamFilter", "1", 0.0, 1.0),
    ranged("statusTextPercentage", "0", 0.0, 1.0),
    ranged("stopAutoAttackOnTargetChange", "0", 0.0, 1.0),
    ranged("targetStatusText", "0", 0.0, 1.0),
    ranged("threatPlaySounds", "1", 0.0, 1.0),
    ranged("threatShowNumeric", "0", 0.0, 1.0),
    ranged("threatWarning", "3", 0.0, 3.0),
    value("toastDuration", "4"),
    ranged("UnitNameEnemyGuardianName", "0", 0.0, 1.0),
    ranged("UnitNameEnemyPetName", "1", 0.0, 1.0),
    ranged("UnitNameEnemyPlayerName", "1", 0.0, 1.0),
    ranged("UnitNameEnemyTotemName", "0", 0.0, 1.0),
    ranged("UnitNameFriendlyGuardianName", "0", 0.0, 1.0),
    ranged("UnitNameFriendlyPetName", "1", 0.0, 1.0),
    ranged("UnitNameFriendlyPlayerName", "1", 0.0, 1.0),
    ranged("UnitNameFriendlyTotemName", "0", 0.0, 1.0),
    ranged("UnitNameNonCombatCreatureName", "0", 0.0, 1.0),
    ranged("UnitNameNPC", "0", 0.0, 1.0),
    ranged("UnitNameOwn", "0", 0.0, 1.0),
    ranged("UnitNamePlayerGuild", "1", 0.0, 1.0),
    ranged("UnitNamePlayerPVPTitle", "1", 0.0, 1.0),
    ranged("useEnglishAudio", "0", 0.0, 1.0),
    ranged("watchFrameWidth", "0", 0.0, 1.0),
    ranged("wholeChatWindowClickable", "1", 0.0, 1.0),
    ranged("xpBarText", "0", 0.0, 1.0),
];
