//! Admitted airborne state, separate from ground input and wire flags.

use glam::{Vec2, Vec3};
use thiserror::Error;

use crate::collision::MovementSupportProfile;
use crate::movement::{MovementFallContactError, MovementFallMode};

/// Native FALLING/FALLING_FAR phase of an active analytic fall.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MovementFallPhase {
    /// Falling before the native far-fall clock/height condition is met.
    Falling,
    /// The far-fall condition or a ceiling reset has been observed.
    FallingFar,
}

/// Explicit fields sampled from the local movement owner, not received flags.
#[derive(Clone, Copy, Debug)]
pub struct MovementFallSnapshot {
    /// Current foot position in the candidate triangles' coordinate space.
    pub position: Vec3,
    /// Unsigned native fall clock in milliseconds.
    pub fall_time_ms: u32,
    /// World Z at the current fall curve's launch.
    pub launch_height: f32,
    /// Signed downward launch speed; upward jumps are negative.
    pub initial_downward_speed: f32,
    /// Native horizontal launch basis, including retained tiny vectors.
    pub horizontal_direction: Vec2,
    /// Current nonnegative horizontal launch speed.
    pub horizontal_speed: f32,
    /// Native full movement basis retained through an active fall.
    pub direction: Vec3,
    /// Resolved terminal-speed mode.
    pub mode: MovementFallMode,
    /// Current native falling phase.
    pub phase: MovementFallPhase,
}

/// An admitted active fall. A landing returns a separate continuation value.
#[derive(Clone, Copy, Debug)]
pub struct MovementFallState {
    pub(super) snapshot: MovementFallSnapshot,
}

impl MovementFallState {
    /// Admits the local owner's finite launch state without normalizing its
    /// already-resolved bases or changing native scalar images.
    ///
    /// # Errors
    /// Returns [`MovementFallAdvanceError::InvalidState`] for non-finite state
    /// or negative horizontal speed.
    pub fn new(snapshot: MovementFallSnapshot) -> Result<Self, MovementFallAdvanceError> {
        if !snapshot.position.is_finite()
            || !snapshot.launch_height.is_finite()
            || !snapshot.initial_downward_speed.is_finite()
            || !snapshot.horizontal_direction.is_finite()
            || !snapshot.horizontal_speed.is_finite()
            || snapshot.horizontal_speed < 0.0
            || !snapshot.direction.is_finite()
        {
            return Err(MovementFallAdvanceError::InvalidState);
        }
        Ok(Self { snapshot })
    }

    /// Returns this active fall's fields for the movement/wire snapshot owner.
    #[must_use]
    pub const fn snapshot(self) -> MovementFallSnapshot {
        self.snapshot
    }
}

/// Native `0x007612B0` trial/live policy and current translation admission.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MovementFallAdvancePolicy {
    /// Step trials suppress live notifications, far-fall promotion, and launch
    /// basis restoration. The trial owner separately saves/restores its fields.
    Trial,
    /// Live fall without any admitted forward/back/strafe input.
    Live,
    /// Live fall with any admitted native translation bit. A nonzero jump
    /// restores its original horizontal speed/bases after collision response.
    LiveTranslating,
}

/// An already-generated displacement and the interval it is allowed to consume.
#[derive(Clone, Copy, Debug)]
pub struct MovementFallInterval {
    /// Unsigned duration in native milliseconds.
    pub duration_ms: u32,
    /// Requested XYZ travel, generated by the movement trajectory owner.
    pub displacement: Vec3,
    /// Admitted body radius in the current collision space.
    pub radius: f32,
    /// Effective body height after movement mode/transport resolution.
    pub height: f32,
    /// Unit-control support policy resolved by the caller.
    pub support_profile: MovementSupportProfile,
    /// Whether this interval is a trial or a live movement update.
    pub policy: MovementFallAdvancePolicy,
}

/// Ownership after the interval: an active fall or a ground transition.
#[derive(Clone, Copy, Debug)]
pub enum MovementFallContinuation {
    /// The returned state owns subsequent fall intervals.
    Airborne(MovementFallState),
    /// Native end-fall was requested by support or blocked-progress handling.
    /// The ground owner clears falling flags, rebuilds its input basis/speed,
    /// and handles pending input before producing the next movement snapshot.
    Landed {
        /// Foot position at the native end-fall boundary.
        position: Vec3,
        /// Unconditional fall time retained even after FALLING clears on wire.
        fall_time_ms: u32,
    },
}

/// Completed collision interval and the actions its movement owner must apply.
#[derive(Clone, Copy, Debug)]
pub struct MovementFallAdvance<Identity = usize> {
    /// Native elapsed-time result, including its float-to-integer conversion.
    pub consumed_ms: u32,
    /// Active fall state or the ground transition's position and fall clock.
    pub continuation: MovementFallContinuation,
    /// Rebase the movement anchor to current position/facing/pitch and clear its
    /// analytic elapsed clock, as on a repeated contact or native end-fall.
    pub reset_motion_anchor: bool,
    /// Live ceiling notification at interval start plus `consumed_ms`. The unit
    /// notification owner still applies its ordinary subject/admission gates.
    pub notify_ceiling_reset: bool,
    /// Live contact identity copied before later probes replace candidates.
    /// Fixed-slice advancement retains the original triangle-index API.
    /// Trials suppress this request; clear travel and ceiling resets clear it.
    pub contact_triangle: Option<Identity>,
    /// A probe could not obtain complete geometry. Prior movement is retained.
    pub geometry_unavailable: bool,
    /// Subtract this from the analytic motion clock, request the controlled
    /// subject's skipped-time notification, and postpone its heartbeat deadline
    /// (`0x006E9B20`). The returned fall state already excludes this
    /// unavailable portion; `consumed_ms` still reports the full interval.
    pub skipped_time_ms: u32,
}

/// Invalid snapshot, geometry, or arithmetic at the fall interval boundary.
#[derive(Clone, Copy, Debug, Error, PartialEq)]
pub enum MovementFallAdvanceError {
    /// The supplied local state cannot represent an admitted active fall.
    #[error("movement fall state is invalid")]
    InvalidState,
    /// A collision or contact-time query rejected its inputs or result.
    #[error(transparent)]
    Contact(#[from] MovementFallContactError),
}
