[package]
name = "solarity-systems"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
glam.workspace = true
shipyard.workspace = true
solarity-asset.workspace = true
solarity-ecs.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true

[dev-dependencies]
glam.workspace = true
wow-m2.workspace = true
wow-mpq.workspace = true
