//! Selection of build-generated SPIR-V and stock specialization constants.

use std::sync::{Arc, OnceLock};

use super::super::{M2PixelShader, M2ShaderPermutation, M2ShaderPlan, M2VertexShader};
use super::source::{
    M2_DIRECT_FRAGMENT_SPIRV, M2_LIQUID_VERTEX_SPIRV, M2_PCF_FRAGMENT_SPIRV, M2_VERTEX_SPIRV,
};
use super::{M2SpirvError, M2SpirvKey, M2SpirvProgram};

/// Selector for immutable M2 bytecode generated during the Cargo build.
pub struct M2SpirvCompiler;

impl M2SpirvCompiler {
    /// Creates one selector for the renderer-owned M2 pipeline cache.
    ///
    /// # Errors
    ///
    /// Build-generated bytecode has no fallible runtime initialization.
    pub fn new() -> Result<Self, M2SpirvError> {
        Ok(Self)
    }

    /// Selects build-generated modules for one exact effect/permutation pair.
    ///
    /// # Errors
    ///
    /// Bytecode validity was enforced by the build script.
    pub fn compile(
        &self,
        plan: M2ShaderPlan,
        permutation: M2ShaderPermutation,
    ) -> Result<M2SpirvProgram, M2SpirvError> {
        let (fragment, fragment_words) = if (permutation.pixel_index() / 4).is_multiple_of(2) {
            (M2_DIRECT_FRAGMENT_SPIRV, &M2_DIRECT_FRAGMENT_WORDS)
        } else {
            (M2_PCF_FRAGMENT_SPIRV, &M2_PCF_FRAGMENT_WORDS)
        };
        Ok(M2SpirvProgram::new(
            M2SpirvKey::new(plan, permutation),
            retained_spirv_words(M2_VERTEX_SPIRV, &M2_VERTEX_WORDS),
            retained_spirv_words(fragment, fragment_words),
            [
                vertex_effect_index(plan.vertex_shader()),
                permutation.vertex_index() as u32,
            ],
            [
                pixel_effect_index(plan.pixel_shader()),
                permutation.pixel_index() as u32,
                u32::from(plan.texture_count()),
            ],
        ))
    }
}

static M2_VERTEX_WORDS: OnceLock<Arc<[u32]>> = OnceLock::new();
static M2_LIQUID_VERTEX_WORDS: OnceLock<Arc<[u32]>> = OnceLock::new();
static M2_DIRECT_FRAGMENT_WORDS: OnceLock<Arc<[u32]>> = OnceLock::new();
static M2_PCF_FRAGMENT_WORDS: OnceLock<Arc<[u32]>> = OnceLock::new();

/// Device capability selects this module while retaining the stock effect key.
pub(super) fn liquid_vertex_words() -> Arc<[u32]> {
    retained_spirv_words(M2_LIQUID_VERTEX_SPIRV, &M2_LIQUID_VERTEX_WORDS)
}

/// Converts each build-generated byte module once and shares it across every
/// specialization-keyed pipeline program.
fn retained_spirv_words(bytes: &[u8], words: &OnceLock<Arc<[u32]>>) -> Arc<[u32]> {
    Arc::clone(words.get_or_init(|| {
        bytes
            .as_chunks::<4>()
            .0
            .iter()
            .map(|word| u32::from_le_bytes([word[0], word[1], word[2], word[3]]))
            .collect()
    }))
}

/// Produces the GLSL compile-time selector for the seven stock vertex effects.
const fn vertex_effect_index(effect: M2VertexShader) -> u32 {
    match effect {
        M2VertexShader::DiffuseT1 => 0,
        M2VertexShader::DiffuseT2 => 1,
        M2VertexShader::DiffuseEnv => 2,
        M2VertexShader::DiffuseT1T2 => 3,
        M2VertexShader::DiffuseEnvT2 => 4,
        M2VertexShader::DiffuseT1Env => 5,
        M2VertexShader::DiffuseEnvEnv => 6,
    }
}

/// Produces the GLSL compile-time selector for every stock pixel combiner.
const fn pixel_effect_index(effect: M2PixelShader) -> u32 {
    match effect {
        M2PixelShader::Opaque => 0,
        M2PixelShader::Mod => 5,
        M2PixelShader::Decal => 1,
        M2PixelShader::Add => 2,
        M2PixelShader::Mod2x => 3,
        M2PixelShader::Fade => 4,
        M2PixelShader::OpaqueOpaque => 6,
        M2PixelShader::OpaqueMod => 11,
        M2PixelShader::OpaqueAdd => 7,
        M2PixelShader::OpaqueMod2x => 8,
        M2PixelShader::OpaqueMod2xNoAlpha => 9,
        M2PixelShader::OpaqueAddNoAlpha => 10,
        M2PixelShader::ModOpaque => 12,
        M2PixelShader::ModMod => 17,
        M2PixelShader::ModAdd => 13,
        M2PixelShader::ModMod2x => 14,
        M2PixelShader::ModMod2xNoAlpha => 15,
        M2PixelShader::ModAddNoAlpha => 16,
        M2PixelShader::AddMod => 18,
        M2PixelShader::Mod2xMod2x => 19,
        M2PixelShader::OpaqueMod2xNoAlphaAlpha => 20,
        M2PixelShader::OpaqueAddAlpha => 21,
        M2PixelShader::OpaqueAddAlphaAlpha => 22,
    }
}
