//! Admitted local ground state and explicit transition actions.

use glam::{Vec2, Vec3};
use thiserror::Error;

use crate::collision::{MovementSupportProfile, MovementSweepError};
use crate::movement::{
    MovementFallAdvanceError, MovementFallError, MovementFallMode, MovementFallPhase,
    MovementFallSnapshot, MovementFallState,
};

/// Unit-control resolution shared by slope support and step height.
#[derive(Clone, Copy, Debug)]
pub enum MovementGroundProfile {
    /// Native controlled-player step height from the unit movement owner.
    PlayerControlled {
        /// Native unit-owned step height in the current collision space.
        step_height: f32,
    },
    /// Native other-unit support policy and two-unit step height.
    Other,
}

impl MovementGroundProfile {
    pub(super) const fn support(self) -> MovementSupportProfile {
        match self {
            Self::PlayerControlled { .. } => MovementSupportProfile::PlayerControlled,
            Self::Other => MovementSupportProfile::Other,
        }
    }
    pub(super) const fn step_height(self) -> f32 {
        match self {
            Self::PlayerControlled { step_height } => step_height,
            Self::Other => 2.0,
        }
    }
}

/// Resolved native start-fall gate, including movement and spline modes.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum MovementFallAdmission {
    /// The movement owner admits `0x00988370`.
    Allowed,
    /// A current movement or spline mode suppresses starting a fall.
    Suppressed,
}

/// Ground-owned position/step state and retained launch fields.
#[derive(Clone, Copy, Debug)]
pub struct MovementGroundSnapshot {
    /// Foot position in the supplied triangles' coordinate space.
    pub position: Vec3,
    /// Active step's original height; `None` means the native step flag is clear.
    pub step_anchor: Option<f32>,
    /// Retained unsigned fall clock, even while grounded.
    pub fall_time_ms: u32,
    /// Retained fall launch height, including speculative step-trial writes.
    pub launch_height: f32,
    /// Retained downward launch speed.
    pub initial_downward_speed: f32,
    /// Resolved ground input basis used when rebasing or starting a fall.
    pub horizontal_direction: Vec2,
    /// Resolved nonnegative ground input speed.
    pub horizontal_speed: f32,
    /// Resolved full ground input basis.
    pub direction: Vec3,
    /// Terminal-speed mode retained on a new fall.
    pub mode: MovementFallMode,
    /// Current start-fall admission, resolved separately from received flags.
    pub fall_admission: MovementFallAdmission,
}

/// Admitted state for native grounded collision intervals.
#[derive(Clone, Copy, Debug)]
pub struct MovementGroundState {
    pub(super) snapshot: MovementGroundSnapshot,
}

impl MovementGroundState {
    /// Admits finite owner state without normalizing its resolved input bases.
    ///
    /// # Errors
    /// Returns an invalid-state error for non-finite fields or negative speed.
    pub fn new(snapshot: MovementGroundSnapshot) -> Result<Self, MovementGroundAdvanceError> {
        if !snapshot.position.is_finite()
            || snapshot.step_anchor.is_some_and(|z| !z.is_finite())
            || !snapshot.launch_height.is_finite()
            || !snapshot.initial_downward_speed.is_finite()
            || !snapshot.horizontal_direction.is_finite()
            || !snapshot.direction.is_finite()
            || !snapshot.horizontal_speed.is_finite()
            || snapshot.horizontal_speed < 0.0
        {
            return Err(MovementGroundAdvanceError::InvalidState);
        }
        Ok(Self { snapshot })
    }

    /// Returns the fields retained by this ground continuation.
    #[must_use]
    pub const fn snapshot(self) -> MovementGroundSnapshot {
        self.snapshot
    }
}

impl MovementGroundSnapshot {
    pub(super) fn start_fall(
        self,
    ) -> Result<Option<MovementFallState>, MovementGroundAdvanceError> {
        if self.fall_admission == MovementFallAdmission::Suppressed {
            return Ok(None);
        }
        Ok(Some(MovementFallState::new(MovementFallSnapshot {
            position: self.position,
            fall_time_ms: 0,
            launch_height: self.position.z,
            initial_downward_speed: 0.0,
            horizontal_direction: self.horizontal_direction,
            horizontal_speed: self.horizontal_speed,
            direction: self.direction,
            mode: self.mode,
            phase: MovementFallPhase::Falling,
        })?))
    }
}

/// Ground displacement already generated by the timestamped input owner.
#[derive(Clone, Copy, Debug)]
pub struct MovementGroundInterval {
    /// Original unsigned duration in milliseconds.
    pub duration_ms: u32,
    /// Native separate horizontal distance image.
    pub distance: f32,
    /// Incoming horizontal direction, already resolved by the input owner.
    pub direction: Vec2,
    /// Admitted body radius.
    pub radius: f32,
    /// Effective body height in the current collision space.
    pub height: f32,
    /// Unit-control profile and owned step height.
    pub profile: MovementGroundProfile,
}

/// Grounded or newly airborne ownership after collision response.
#[derive(Clone, Copy, Debug)]
pub enum MovementGroundContinuation {
    /// Retain this state for the next ground interval.
    Grounded(MovementGroundState),
    /// Start the fall curve at this state and process remaining owner time.
    Falling(MovementFallState),
}

/// Native consumed time and actions for the outer movement/notification owner.
#[derive(Clone, Copy, Debug)]
pub struct MovementGroundAdvance<Identity = usize> {
    /// Original duration, except successful start-fall with an empty candidate set.
    pub consumed_ms: u32,
    /// State that owns the next interval.
    pub continuation: MovementGroundContinuation,
    /// Rebase position/facing/pitch and clear the analytic elapsed clock.
    pub reset_motion_anchor: bool,
    /// Selected candidate identity, copied before later probes replace geometry.
    /// Fixed-slice advancement retains the original index API.
    pub contact_triangle: Option<Identity>,
    /// At least one ground/step/fall probe could not obtain complete geometry.
    /// The continuation preserves native writes made before that failure.
    pub geometry_unavailable: bool,
    /// Skipped-time notification and heartbeat postponement for the controlled
    /// subject after failed private fall trials (`0x006E9B20`). Their own motion
    /// clock changes are restored by the trial owner.
    pub skipped_time_ms: u32,
}

/// Admission or arithmetic failure at the pure grounded interval boundary.
#[derive(Clone, Copy, Debug, Error, PartialEq)]
pub enum MovementGroundAdvanceError {
    /// Non-finite state or invalid step/travel scalars.
    #[error("movement ground state or interval is invalid")]
    InvalidState,
    /// Invalid collision volume or query.
    #[error(transparent)]
    Collision(#[from] MovementSweepError),
    /// Speculative falling interval failed admission.
    #[error(transparent)]
    Fall(#[from] MovementFallAdvanceError),
    /// Speculative fall curve could not be represented.
    #[error(transparent)]
    Trajectory(#[from] MovementFallError),
}
